// AUTH
export const SET_USERNAME = "SET_USERNAME";

// MESSAGES
export const SET_SELECTED_CHANNEL = "SET_SELECTED_CHANNEL";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";

export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";

// Projects
export const FETCH_PROJECTS_BEGIN = "FETCH_PROJECTS_BEGIN";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const CREATE_PROJECT_BEGIN = "CREATE_PROJECT_BEGIN";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

// Channels
export const CREATE_CHANNEL_BEGIN = "CREATE_CHANNEL_BEGIN";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAIL = "CREATE_CHANNEL_FAIL";

export const DELETE_CHANNEL_BEGIN = "DELETE_CHANNEL_BEGIN";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";
export const DELETE_CHANNEL_FAIL = "DELETE_CHANNEL_FAIL";

// Messages
export const CREATE_MESSAGE_BEGIN = "CREATE_MESSAGE_BEGIN";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const DELETE_MESSAGE_BEGIN = "DELETE_MESSAGE_BEGIN";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

// MODAL
export const CHANNEL_MODAL_OPEN = "CHANNEL_MODAL_OPEN";
export const CHANNEL_MODAL_CLOSE = "CHANNEL_MODAL_CLOSE";
export const PROJECT_MODAL_OPEN = "PROJECT_MODAL_OPEN";
export const PROJECT_MODAL_CLOSE = "PROJECT_MODAL_CLOSE";
