// AUTH
export const SET_USERNAME = "SET_USERNAME";

// MESSAGES
export const CHANGE_CHANNEL = "CHANGE_CHANNEL";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const DELETE_CHANNEL = "DELETE_CHANNEL";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const SET_SELECTED_PROJECT = "SET_SELECTED_CHANNEL";

// MODAL
export const CHANNEL_MODAL_OPEN = "CHANNEL_MODAL_OPEN";
export const CHANNEL_MODAL_CLOSE = "CHANNEL_MODAL_CLOSE";
export const PROJECT_MODAL_OPEN = "PROJECT_MODAL_OPEN";
export const PROJECT_MODAL_CLOSE = "PROJECT_MODAL_CLOSE";
